# Collector Configurations

# Debug mode
debug: true

# LogFile
logFile: /opt/nfcollector/var/log/collector.log

# Listen on address & port
listen:
  # Listen Address
  address: 0.0.0.0

  # Listen Port
  port: 6859

# Forwarder configuration
forwarder:
  # Enable
  enabled: true

  # Host to forward
  hosts:
    - 127.0.0.1
    - 192.168.1.1
    - 10.20.3.15

  # Port to forward
  port: 7161

# Exporters
exporter:
  # InfluxDB exporter
  # you can config as many as you want
  influxDBs:
    - host: 127.0.0.1
      port: 8086
      #username: user
      #password: secret
      database: dbNetflow

    - host: 127.0.0.2
      port: 8087
      #username: user
      #password: secret
      database: dbNetflow2
